"""initial migration

Revision ID: 761b0c4190fd
Revises: 
Create Date: 2021-05-15 13:28:51.176050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761b0c4190fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), server_default='', nullable=False),
    sa.Column('password', sa.String(length=128), server_default='pbkdf2:sha256:150000$1rUi61gD$faa3b96615044dcdca50810cf7f82de06f157967b99365b86715cefec9e4d0cf', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), server_default='', nullable=False),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('text', sa.Text(), server_default='', nullable=True),
    sa.Column('cover_image', sa.String(), server_default='', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_tag_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag_links')
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
