"""Add cover_image field in Post model

Revision ID: e2eee0b72f9b
Revises: 1b7d4b0db88e
Create Date: 2021-05-10 12:45:58.718557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2eee0b72f9b'
down_revision = '1b7d4b0db88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image', sa.String(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image')
    # ### end Alembic commands ###
